INSERT INTO laravel8.users (id, user_id, name, email, email_verified_at, password, remember_token, created_at, updated_at) VALUES (1, 'tom', '친절한 톰아저씨', 'tomcruise@topgun.com', null, '$2y$10$6yM773s/II05rQ0qg9MQ4.XmTVaNXYM0j9XxmKybhlcawhDD9um1K', null, null, null);
INSERT INTO laravel8.users (id, user_id, name, email, email_verified_at, password, remember_token, created_at, updated_at) VALUES (2, 'tom_member', '톰아저씨 추종자', 'like-tom@example.com', null, '$2y$10$6yM773s/II05rQ0qg9MQ4.XmTVaNXYM0j9XxmKybhlcawhDD9um1K', null, null, null);
INSERT INTO laravel8.users (id, user_id, name, email, email_verified_at, password, remember_token, created_at, updated_at) VALUES (3, 'tom_intern', '톰아저씨 맹신자', 'love-tom@example.com', null, '$2y$10$6yM773s/II05rQ0qg9MQ4.XmTVaNXYM0j9XxmKybhlcawhDD9um1K', null, null, null);
INSERT INTO laravel8.users (id, user_id, name, email, email_verified_at, password, remember_token, created_at, updated_at) VALUES (4, 'amanda', '아만다 사이프리드', 'amanda@example.com', null, '$2y$10$6yM773s/II05rQ0qg9MQ4.XmTVaNXYM0j9XxmKybhlcawhDD9um1K', null, null, null);
INSERT INTO laravel8.users (id, user_id, name, email, email_verified_at, password, remember_token, created_at, updated_at) VALUES (5, 'amanda_member', '아만다 추종자', 'like-amanda@example.com', null, '$2y$10$6yM773s/II05rQ0qg9MQ4.XmTVaNXYM0j9XxmKybhlcawhDD9um1K', null, null, null);
INSERT INTO laravel8.users (id, user_id, name, email, email_verified_at, password, remember_token, created_at, updated_at) VALUES (6, 'amanda_intern', '아만다 맹신자', 'love-amanda@example.com', null, '$2y$10$6yM773s/II05rQ0qg9MQ4.XmTVaNXYM0j9XxmKybhlcawhDD9um1K', null, null, null);
INSERT INTO laravel8.users (id, user_id, name, email, email_verified_at, password, remember_token, created_at, updated_at) VALUES (7, 'chanho', '멋진 찬호아저씨', 'chanho@example.com', null, '$2y$10$6yM773s/II05rQ0qg9MQ4.XmTVaNXYM0j9XxmKybhlcawhDD9um1K', null, null, null);
INSERT INTO laravel8.users (id, user_id, name, email, email_verified_at, password, remember_token, created_at, updated_at) VALUES (8, 'chanho_member', '멋진 찬호아저씨 추종자', 'like-chanho@example.com', null, '$2y$10$6yM773s/II05rQ0qg9MQ4.XmTVaNXYM0j9XxmKybhlcawhDD9um1K', null, null, null);
INSERT INTO laravel8.users (id, user_id, name, email, email_verified_at, password, remember_token, created_at, updated_at) VALUES (9, 'chanho_intern', '멋진 찬호아저씨 맹신자', 'love-chanho@example.com', null, '$2y$10$6yM773s/II05rQ0qg9MQ4.XmTVaNXYM0j9XxmKybhlcawhDD9um1K', null, null, null);
