<?php

namespace Tests\Feature;

use App\Models\Customer;
use App\Models\CustomersPoint;
use App\Models\PointEvent;
use App\Services\AddPointService;
use Carbon\CarbonImmutable;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AddPointServiceTest extends TestCase
{
    use RefreshDatabase;

    const CUSTOMER_ID = 1;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Customer::factory()->create([
           'id' => self::CUSTOMER_ID
        ]);

        CustomersPoint::unguard(); //모델의 대량할당 보호를 일시적으로 비활성화.
        CustomersPoint::create(
        [
            'customer_id' => self::CUSTOMER_ID,
            'point' => 100
        ]);
        CustomersPoint::reguard();
    }

    /**
     * @test
     */
    public function add()
    {
        $event = new PointEvent(self::CUSTOMER_ID, '추가 이벤트', 10, CarbonImmutable::create(2018, 8, 4, 12, 34, 56));

//        $service = app()->make(AddPointService::class);
        $service = app(AddPointService::class);
        $service->add($event);

        $this->assertDatabaseHas(
            'customers_points_events',
            [
                'customer_id' => self::CUSTOMER_ID,
                'event' => $event->getEvent(),
                'point' => $event->getPoint(),
                'created_at' => $event->getCreatedAt()
            ]
        );

        $this->assertDatabaseHas(
            'customers_points',
            [
                'customer_id' => self::CUSTOMER_ID,
                'point' => 110
            ]
        );
    }

}
